import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Outfit } from "next/font/google";   // ✅ add this
import "./globals.css";
import { Navbar } from "@/foodie-components/Navbar";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({   // ✅ outline-style font
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable}`}
      >
        <Navbar/>
        {children}
        <AboutUs/>

      </body>
    </html>
  );
}
export function AboutUs() {
    return (
      <footer className="relative Central_Default w-screen overflow-visible bottom-0">
        <div className="w-full h-48">
          <Image src="http://lekvilla.com/wp-content/uploads/2015/07/BACKGROUND-FOOTER-1.jpg" alt="Food" fill  unoptimized priority/>
        </div>
                <div className="absolute bottom-10 w-full grid grid-cols-2 text-center text-white font-[outfit]  font-semibold">
                    <div>Contact Us</div>
                    <div>Sponsors</div>
                    <div>Mobile App</div>
                    <div>Founders</div>
                    <div>Our Achievements</div>
                    <p>Our Team</p>
                </div>
            </footer>
    );
}
  